window.METEO_CATALOG = {
  scenes: [
    {
      id: 'synoptic',
      title: '天气形势分析',
      subtitle: '高低压、槽线、切变线与锋面综合研判',
      icon: '◒',
      gradient: 'scene-blue',
      experts: ['synoptic-expert', 'heavy-rain-expert', 'gis-expert'],
    },
    {
      id: 'severe-weather',
      title: '灾害天气',
      subtitle: '强降水、强对流与风险区域分析',
      icon: 'ϟ',
      gradient: 'scene-purple',
      experts: ['heavy-rain-expert', 'convection-expert', 'forecast-team'],
    },
    {
      id: 'content',
      title: '产品制作',
      subtitle: '预报稿、专题材料、Word 与 PPT 成果物',
      icon: '✦',
      gradient: 'scene-amber',
      experts: ['writing-expert', 'office-expert', 'research-team'],
    },
    {
      id: 'data',
      title: '数据与科研',
      subtitle: 'NC/GRIB 分析、算法调试与项目材料',
      icon: '⌁',
      gradient: 'scene-cyan',
      experts: ['data-expert', 'algorithm-expert', 'research-team'],
    },
  ],
  experts: [
    {
      id: 'synoptic-expert',
      kind: 'expert',
      name: '天气形势分析专家',
      owner: '气象业务组',
      category: '天气分析',
      avatar: '形',
      description: '综合地面与高空场，组织高低压、槽线、切变线、锋面和急流等天气系统分析。',
      tags: ['形势分析', '天气系统', '业务研判'],
      instruction: '先说明数据时次、模式和区域，再分层分析地面、850hPa、500hPa 和高空急流。结论必须引用工具返回的结构化事实；没有数据时明确列出缺口。',
      prompts: ['分析今天 08 时东亚地区天气形势', '根据诊断结果生成未来三天形势演变', '检查槽线、切变线与降水落区是否一致'],
    },
    {
      id: 'heavy-rain-expert',
      kind: 'expert',
      name: '强降水诊断专家',
      owner: '灾害天气组',
      category: '灾害天气',
      avatar: '雨',
      description: '围绕水汽、动力、热力和不稳定条件，生成强降水评分、风险区域和证据链。',
      tags: ['强降水', '风险评分', '证据链'],
      instruction: '按照水汽、动力抬升、热力不稳定、持续时间和模式一致性组织强降水诊断，并区分短时强降水与过程性强降水。',
      prompts: ['评估未来 24 小时强降水风险', '解释高风险区的关键物理量', '生成强降水专题分析提纲'],
    },
    {
      id: 'convection-expert',
      kind: 'expert',
      name: '强对流风险专家',
      owner: '短临预报组',
      category: '灾害天气',
      avatar: '雷',
      description: '分析冰雹、雷暴大风、短时强降水和龙卷等强对流风险及触发条件。',
      tags: ['强对流', '雷暴大风', '冰雹'],
      instruction: '从触发、垂直风切变、CAPE、低层水汽和抑制条件分析强对流，分别输出不同灾害类型的概率与置信度。',
      prompts: ['分析今天下午强对流潜势', '比较雷暴大风与冰雹风险', '生成强对流风险提示'],
    },
    {
      id: 'writing-expert',
      kind: 'expert',
      name: '气象智能写稿专家',
      owner: '产品服务组',
      category: '内容创作',
      avatar: '稿',
      description: '根据结构化气象结论和业务模板，生成短期预报、专题材料、周报和决策服务稿。',
      tags: ['智能写稿', '决策服务', '业务模板'],
      instruction: '先校验事实与时次，再按业务模板写稿。禁止把推测写成实况；风险用语、时间范围和区域名称必须准确。',
      prompts: ['生成未来三天天气预报稿', '把诊断结论改写成决策服务材料', '根据模板生成重大天气专题稿'],
    },
    {
      id: 'office-expert',
      kind: 'expert',
      name: '气象办公文件助手',
      owner: '综合办公室',
      category: '办公效率',
      avatar: '办',
      description: '整理 Word、Excel、PPT、PDF 和图片资料，生成可交付的气象办公成果。',
      tags: ['Word', 'Excel', 'PPT'],
      instruction: '先识别目标成果物、模板和数据来源，再生成结构化内容。对二进制办公文件优先调用专用 Artifact MCP，不直接破坏文件格式。',
      prompts: ['整理本周材料并生成周报', '根据表格生成降水统计汇报', '把分析报告改成 10 页 PPT 提纲'],
    },
    {
      id: 'data-expert',
      kind: 'expert',
      name: '气象数据分析师',
      owner: '数据研发组',
      category: '数据智能',
      avatar: '数',
      description: '读取和检查 NC、GRIB、站点与网格数据，生成统计、图表和异常说明。',
      tags: ['NetCDF', 'GRIB', '统计分析'],
      instruction: '记录数据文件、变量、单位、坐标、缺测值和时空范围。计算前先检查维度与单位，输出可复现的处理步骤。',
      prompts: ['检查这个 NC 文件的数据结构', '统计区域累计降水并生成表格', '比较两个模式的温度偏差'],
    },
    {
      id: 'gis-expert',
      kind: 'expert',
      name: '气象 GIS 制图助手',
      owner: '可视化组',
      category: '数据智能',
      avatar: '图',
      description: '组织等值线、色斑图、天气系统和站点标注，生成适合业务发布的地图成果。',
      tags: ['GIS', '天气图', '制图'],
      instruction: '明确投影、范围、图层顺序、色标、单位、时间和数据源。制图结果要附带图例和质量检查项。',
      prompts: ['生成 24 小时累计降水图方案', '优化天气系统叠加图层', '检查色标、图例和标注是否规范'],
    },
    {
      id: 'algorithm-expert',
      kind: 'expert',
      name: '气象算法开发工程师',
      owner: '算法研发组',
      category: '技术工程',
      avatar: '码',
      description: '面向气象诊断算法、数据处理脚本和服务接口，分析代码、修改文件并运行测试。',
      tags: ['算法开发', 'Python', '代码审查'],
      instruction: '先阅读项目结构和现有测试，再提出最小修改方案。涉及文件修改时只在用户授权的工作区操作，并在结束前运行相关测试。',
      prompts: ['分析当前槽线算法并提出优化方案', '修复单元测试失败并说明原因', '为气象诊断接口补充测试'],
      fileToolsRecommended: true,
    },
  ],
  teams: [
    {
      id: 'forecast-team',
      kind: 'team',
      name: '重大天气过程研判专家团',
      owner: '联合会商',
      category: '专家团',
      avatar: '会',
      description: '形势分析、强降水、强对流、历史相似过程和质量审核协同完成过程研判。',
      tags: ['会商', '多专家', '过程研判'],
      instruction: '按形势背景、灾害风险、模式差异、历史相似过程、结论审核五个角色组织协作，最后合并为一份有证据链的会商材料。',
      prompts: ['组织一次重大天气过程会商', '生成会商材料和风险清单', '对多个模式结论做一致性审核'],
    },
    {
      id: 'product-team',
      kind: 'team',
      name: '日常预报产品生产专家团',
      owner: '业务产品组',
      category: '专家团',
      avatar: '产',
      description: '从数据检查、天气分析、稿件生成、配图到质量审核完成日常产品生产。',
      tags: ['产品流水线', '写稿', '审核'],
      instruction: '按照数据检查、分析结论、稿件、图表、审核清单的顺序执行，任何缺少数据依据的结论必须标记为待确认。',
      prompts: ['生成今天的完整预报产品包', '根据模板生产周报和配图', '检查稿件与天气图是否一致'],
    },
    {
      id: 'research-team',
      kind: 'team',
      name: '气象科研项目材料专家团',
      owner: '科研管理组',
      category: '专家团',
      avatar: '研',
      description: '协助方案调研、数据分析、算法说明、项目文档和汇报材料生产。',
      tags: ['科研项目', '方案设计', '汇报材料'],
      instruction: '区分研究假设、已有证据、实验结果和后续计划，生成可追溯的项目材料，不夸大算法效果。',
      prompts: ['整理项目阶段成果并生成汇报', '设计算法评测方案', '生成项目验收材料目录'],
    },
  ],
  skills: [
    { id: 'skill-synoptic', name: '天气形势综合分析', category: '天气分析', icon: '形', description: '按层次组织天气系统、环流背景和演变逻辑。', status: '内置规划' },
    { id: 'skill-rain', name: '强降水风险评分', category: '灾害天气', icon: '雨', description: '综合水汽、动力、热力、持续性和模式一致性。', status: '待接算法' },
    { id: 'skill-writing', name: '预报稿件生成', category: '内容创作', icon: '稿', description: '基于结构化结论和模板生成气象业务稿件。', status: 'MVP 可用' },
    { id: 'skill-word', name: 'Word 模板填充', category: '办公效率', icon: 'W', description: '替换占位符、插入图片、保留段落和表格样式。', status: '待接 MCP' },
    { id: 'skill-excel', name: 'Excel 统计与制图', category: '办公效率', icon: 'X', description: '读取表格、统计指标、公式和图表。', status: '待接 MCP' },
    { id: 'skill-ppt', name: 'PPT 汇报生成', category: '办公效率', icon: 'P', description: '从提纲和图表生成汇报型演示文稿。', status: '待接 MCP' },
    { id: 'skill-pdf', name: 'PDF 资料摘要', category: '知识检索', icon: 'D', description: '解析、引用和总结技术资料与业务规范。', status: '待接 MCP' },
    { id: 'skill-nc', name: 'NC / GRIB 数据检查', category: '数据智能', icon: '数', description: '检查变量、维度、单位、缺测和时空坐标。', status: '待接 MCP' },
  ],
  connectors: [
    { id: 'connector-goose', name: 'Goose Runtime', category: '运行时', icon: 'G', description: '本地 Agent Runtime，负责模型调用、Skills、MCP 和任务执行。', status: 'runtime' },
    { id: 'connector-data', name: '气象数据中心', category: '气象数据', icon: '云', description: '接入实况、模式、雷达、卫星、站点和格点数据。', status: 'planned' },
    { id: 'connector-diagnosis', name: '天气诊断算法服务', category: '气象算法', icon: '诊', description: '槽线、切变线、锋面、高低压和灾害天气评分。', status: 'planned' },
    { id: 'connector-gis', name: 'GIS 制图服务', category: '气象制图', icon: '图', description: '生成等值线、色斑图、天气系统图层和地图快照。', status: 'planned' },
    { id: 'connector-artifact', name: 'Office Artifact Service', category: '办公成果物', icon: '档', description: '结构化生成 DOCX、XLSX、PPTX、PDF 和 HTML。', status: 'planned' },
    { id: 'connector-knowledge', name: '气象知识库', category: '知识检索', icon: '知', description: '检索规范、教材、历史过程、预报总结和内部资料。', status: 'planned' },
  ],
};
