const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('meteoDesktop', {
  getAccountState: () => ipcRenderer.invoke('auth:state'),
  loginAccount: (request) => ipcRenderer.invoke('auth:login', request),
  openOfflineAccount: () => ipcRenderer.invoke('auth:offline'),
  logoutAccount: () => ipcRenderer.invoke('auth:logout'),
  changeAccountPassword: (request) => ipcRenderer.invoke('auth:change-password', request),
  claimLegacyProfileData: () => ipcRenderer.invoke('auth:claim-legacy'),
  getDesktopPreferences: () => ipcRenderer.invoke('auth:preferences'),
  saveDesktopPreferences: (request) => ipcRenderer.invoke('auth:preferences-save', request),
  refreshRuntimePreferences: () => ipcRenderer.invoke('runtime:preferences-refresh'),
  setWindowMode: (mode) => ipcRenderer.invoke('window:mode', mode),
  platform: process.platform,
  windowMinimize: () => ipcRenderer.invoke('window:minimize'),
  windowToggleMaximize: () => ipcRenderer.invoke('window:toggle-maximize'),
  windowClose: () => ipcRenderer.invoke('window:close'),
  windowIsMaximized: () => ipcRenderer.invoke('window:is-maximized'),
  onWindowStateChange: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('window:state', listener);
    return () => ipcRenderer.removeListener('window:state', listener);
  },

  getRuntimeStatus: () => ipcRenderer.invoke('runtime:status'),
  getModelSettings: () => ipcRenderer.invoke('runtime:model-settings'),
  saveModelSettings: (request) => ipcRenderer.invoke('runtime:model-settings-save', request),
  createModelProvider: (request) => ipcRenderer.invoke('runtime:model-provider-create', request),
  updateModelProvider: (request) => ipcRenderer.invoke('runtime:model-provider-update', request),
  deleteModelProvider: (request) => ipcRenderer.invoke('runtime:model-provider-delete', request),
  saveCustomModel: (request) => ipcRenderer.invoke('runtime:custom-model-save', request),
  deleteCustomModel: (request) => ipcRenderer.invoke('runtime:custom-model-delete', request),
  getDefaultAssistantWorkspace: () => ipcRenderer.invoke('workspace:assistant-default'),
  getDefaultProjectWorkspace: () => ipcRenderer.invoke('workspace:project-default'),
  createProjectWorkspace: (request) => ipcRenderer.invoke('workspace:project-create', request),
  chooseWorkspace: (request) => ipcRenderer.invoke('workspace:choose', request),
  listWorkspaceFiles: (request) => ipcRenderer.invoke('workspace:list-files', request),
  openWorkspace: (targetPath) => ipcRenderer.invoke('workspace:open', targetPath),
  openExternalUrl: (targetUrl) => ipcRenderer.invoke('external:open', targetUrl),
  listKnowledgeSources: () => ipcRenderer.invoke('knowledge:list'),
  importLocalKnowledgeSources: (request) => ipcRenderer.invoke('knowledge:import-local', request),
  saveKnowledgeSource: (request) => ipcRenderer.invoke('knowledge:save', request),
  testKnowledgeSource: (request) => ipcRenderer.invoke('knowledge:test', request),
  setKnowledgeSourceEnabled: (request) => ipcRenderer.invoke('knowledge:set-enabled', request),
  updateKnowledgeSourceProjects: (request) => ipcRenderer.invoke('knowledge:update-projects', request),
  deleteKnowledgeSource: (id) => ipcRenderer.invoke('knowledge:delete', id),
  sendRuntimeMessage: (request) => ipcRenderer.invoke('runtime:send', request),
  cancelRuntimeTask: (request) => ipcRenderer.invoke('runtime:cancel', request),
  resolvePermission: (request) => ipcRenderer.invoke('runtime:permission', request),

  listCapabilities: () => ipcRenderer.invoke('capability:list'),
  chooseSkillFile: () => ipcRenderer.invoke('capability:choose-skill-file'),
  chooseSkillDirectory: () => ipcRenderer.invoke('capability:choose-skill-directory'),
  inspectSkill: (sourcePath) => ipcRenderer.invoke('capability:inspect-skill', sourcePath),
  inspectBundledSkill: (skillId) => ipcRenderer.invoke('capability:inspect-bundled-skill', skillId),
  installSkill: (request) => ipcRenderer.invoke('capability:install-skill', request),
  setSkillEnabled: (request) => ipcRenderer.invoke('capability:set-skill-enabled', request),
  uninstallSkill: (id) => ipcRenderer.invoke('capability:uninstall-skill', id),
  updateSkillProjects: (request) => ipcRenderer.invoke('capability:update-skill-projects', request),
  saveConnector: (request) => ipcRenderer.invoke('capability:save-connector', request),
  testConnector: (request) => ipcRenderer.invoke('capability:test-connector', request),
  setConnectorEnabled: (request) => ipcRenderer.invoke('capability:set-connector-enabled', request),
  deleteConnector: (id) => ipcRenderer.invoke('capability:delete-connector', id),
  updateConnectorProjects: (request) => ipcRenderer.invoke('capability:update-connector-projects', request),
  saveExpert: (request) => ipcRenderer.invoke('capability:save-expert', request),
  setExpertStatus: (request) => ipcRenderer.invoke('capability:set-expert-status', request),
  migrateExperts: (items) => ipcRenderer.invoke('capability:migrate-experts', items),
  resolveExpertConflict: (request) => ipcRenderer.invoke('capability:resolve-expert-conflict', request),
  openCapabilityPath: (targetPath) => ipcRenderer.invoke('capability:open-path', targetPath),

  listSkillDrafts: () => ipcRenderer.invoke('skill-creator:list-drafts'),
  createSkillDraft: (request) => ipcRenderer.invoke('skill-creator:create-draft', request),
  getSkillDraft: (id) => ipcRenderer.invoke('skill-creator:get-draft', id),
  readSkillDraftFile: (request) => ipcRenderer.invoke('skill-creator:read-file', request),
  writeSkillDraftFile: (request) => ipcRenderer.invoke('skill-creator:write-file', request),
  validateSkillDraft: (id) => ipcRenderer.invoke('skill-creator:validate-draft', id),
  exportSkillDraft: (request) => ipcRenderer.invoke('skill-creator:export-draft', request),
  installSkillDraft: (request) => ipcRenderer.invoke('skill-creator:install-draft', request),
  deleteSkillDraft: (id) => ipcRenderer.invoke('skill-creator:delete-draft', id),
  openSkillDraft: (id) => ipcRenderer.invoke('skill-creator:open-draft', id),

  getSkillHubSettings: () => ipcRenderer.invoke('skillhub:get-settings'),
  saveSkillHubSettings: (request) => ipcRenderer.invoke('skillhub:save-settings', request),
  testSkillHub: () => ipcRenderer.invoke('skillhub:test'),
  listSkillHubSkills: (request) => ipcRenderer.invoke('skillhub:list-skills', request),
  listManagedSkillHubSkills: (request) => ipcRenderer.invoke('skillhub:list-managed-skills', request),
  listSkillHubExperts: (request) => ipcRenderer.invoke('skillhub:list-experts', request),
  syncSkillHubExperts: () => ipcRenderer.invoke('skillhub:sync-experts'),
  listSkillHubPublishers: () => ipcRenderer.invoke('skillhub:list-publishers'),
  updateSkillHubSkill: (request) => ipcRenderer.invoke('skillhub:update-skill', request),
  publishSkillHubVersion: (request) => ipcRenderer.invoke('skillhub:publish-version', request),
  deprecateSkillHubVersion: (request) => ipcRenderer.invoke('skillhub:deprecate-version', request),
  listSkillHubCollections: () => ipcRenderer.invoke('skillhub:list-collections'),
  getSkillHubRecommendations: (request) => ipcRenderer.invoke('skillhub:recommendations', request),
  getSkillHubSkill: (id) => ipcRenderer.invoke('skillhub:get-skill', id),
  downloadSkillHubSkill: (request) => ipcRenderer.invoke('skillhub:download-inspect', request),
  reportSkillHubInstallation: (request) => ipcRenderer.invoke('skillhub:report-installation', request),
  reportSkillHubUninstallation: (request) => ipcRenderer.invoke('skillhub:report-uninstallation', request),
  publishSkillDraftToHub: (request) => ipcRenderer.invoke('skillhub:publish-draft', request),

  onRuntimeEvent: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('runtime:event', listener);
    return () => ipcRenderer.removeListener('runtime:event', listener);
  },
});
