window.METEOMATE_SKILLS = Object.freeze([]);

window.METEOMATE_SKILL_ROADMAP = Object.freeze([
  {
    id: 'nc-grib-inspection',
    name: 'NC / GRIB 数据检查',
    category: '数据智能',
    icon: 'NC',
    description: '检查变量、维度、单位、坐标、缺测值和时空范围。',
    status: 'planned',
    maturity: 'planned',
    tags: ['NetCDF', 'GRIB', '元数据'],
  },
  {
    id: 'office-template-center',
    name: 'Office 模板中心',
    category: '办公成果物',
    icon: '模',
    description: '扫描模板锚点、管理版本并发布可复用的业务模板。',
    status: 'planned',
    maturity: 'planned',
    tags: ['模板', '锚点', '版本'],
  },
  {
    id: 'office-live-editing',
    name: 'Office 实时编辑',
    category: '办公成果物',
    icon: '协',
    description: '在明确的所见即所得或协作需求下接入实时编辑能力。',
    status: 'planned',
    maturity: 'planned',
    tags: ['编辑', '协作', 'Office'],
  },
]);

window.METEOMATE_CONNECTORS = Object.freeze([
  {
    id: 'cua-desktop',
    name: '桌面应用操作',
    category: '桌面与自动化',
    icon: '控',
    description: '读取本机应用窗口，并在授权后完成点击、输入和键盘操作。',
    status: 'available',
    maturity: 'beta',
    tags: ['Cua Driver', '桌面', '自动化'],
    preset: window.MeteoMateComputerConnector.PRESET,
  },
  {
    id: 'playwright-browser',
    name: '浏览器操作',
    category: '网页与自动化',
    icon: '览',
    description: '打开网页、读取内容、截图，并完成点击、输入和表单操作。',
    status: 'available',
    maturity: 'beta',
    tags: ['Playwright', '网页', '自动化'],
    preset: window.MeteoMateBrowserConnector.PRESET,
  },
  {
    id: 'local-workspace',
    name: '本地项目工作区',
    category: '文件与项目',
    icon: '夹',
    description: '授权本地项目目录，使用真实路径与符号链接边界检查限制文件访问。',
    status: 'beta',
    maturity: 'beta',
    tags: ['文件', '项目', '本机资源', '共享目录'],
  },
  {
    id: 'weather-data',
    name: '气象数据中心',
    category: '气象数据',
    icon: '数',
    description: '读取项目配置的本地 JSON/CSV/GeoJSON 或内网 HTTP/HTTPS 气象资料源，同时保留构造演示案例。',
    status: 'beta',
    maturity: 'beta',
    tags: ['真实数据', '构造数据', '站点', '高空场', '模式', 'Evidence'],
    preset: {
      id: 'weather-data',
      name: '气象数据中心',
      description: '读取本地与内网真实资料源及内置构造案例，并生成带来源、时次、单位和摘要的 Evidence。',
      version: '1.1.0',
      transport: 'stdio',
      command: 'MeteoMate Runtime',
      args: [],
      timeout: 30,
      riskClassification: 'medium',
      connectorType: 'weather-data',
      toolAllowlist: [
        'weather_list_sources',
        'weather_query_dataset',
        'weather_validate_dataset',
        'weather_build_evidence',
        'weather_list_cases',
        'weather_get_case',
        'weather_get_station_observations',
        'weather_get_upper_air',
        'weather_compare_guidance',
        'weather_export_demo_bundle',
      ],
    },
  },
  {
    id: 'weather-diagnosis',
    name: '天气诊断算法服务',
    category: '气象算法',
    icon: '诊',
    description: '对标准化真实资料执行可解释的形势、强降水和强对流诊断；构造案例继续用于回归测试。',
    status: 'beta',
    maturity: 'beta',
    tags: ['诊断', '天气系统', '强降水', '强对流', '评分', 'Evidence'],
    preset: {
      id: 'weather-diagnosis',
      name: '天气诊断算法服务',
      description: '按透明规则和固定算法版本计算诊断结果，并返回逐项 Evidence。',
      version: '1.1.0',
      transport: 'stdio',
      command: 'MeteoMate Runtime',
      args: [],
      timeout: 30,
      riskClassification: 'low',
      connectorType: 'weather-diagnosis',
      toolAllowlist: [
        'weather_diagnose_dataset',
        'weather_diagnose_synoptic',
        'weather_diagnose_heavy_rain',
        'weather_diagnose_convection',
      ],
    },
  },
  {
    id: 'gis-map',
    name: 'GIS 制图服务',
    category: '气象可视化',
    icon: '图',
    description: '把标准化气象资料、诊断评分和 Evidence 生成工作区内可预览的风险图。',
    status: 'beta',
    maturity: 'beta',
    tags: ['GIS', '风险图', '站点标注', '成果物', '血缘'],
    preset: {
      id: 'gis-map',
      name: 'GIS 制图服务',
      description: '生成带资料来源、成熟度、Evidence 引用和内容摘要的 HTML 业务示意图。',
      version: '1.1.0',
      transport: 'stdio',
      command: 'MeteoMate Runtime',
      args: [],
      timeout: 30,
      riskClassification: 'medium',
      connectorType: 'gis-map',
      toolAllowlist: ['weather_render_dataset_map', 'weather_render_risk_map'],
    },
  },
  {
    id: 'office-artifacts',
    name: 'Office 成果物',
    category: '办公成果物',
    icon: '文',
    description: '在项目内创建、编辑、渲染和校验 DOCX、PPTX、XLSX 与 PDF 成果物。',
    status: 'available',
    maturity: 'beta',
    tags: ['DOCX', 'PPTX', 'XLSX', 'PDF', '渲染', '校验'],
    preset: window.MeteoMateOfficeConnector.PRESET,
  },
  {
    id: 'knowledge-base',
    name: '气象知识库',
    category: '知识服务',
    icon: '知',
    description: '检索业务规范、历史过程、技术手册、论文和内部资料。',
    status: 'beta',
    maturity: 'beta',
    tags: ['知识库', 'RAG', '引用', '内网接口'],
  },
  {
    id: 'operations-observability',
    name: '监控与日志平台',
    category: '运维保障',
    icon: '监',
    description: '接入服务健康状态、主机与容器指标、告警、日志和发布变更记录。',
    status: 'planned',
    maturity: 'planned',
    tags: ['监控', '日志', '告警'],
  },
]);
