window.METEOMATE_SKILLS = Object.freeze([
  {
    id: 'synoptic-analysis',
    name: '天气形势综合分析',
    category: '天气分析',
    icon: '形',
    description: '按地面、低层、中层和高空急流组织天气系统与演变分析。',
    status: 'built-in',
    tags: ['形势', '槽线', '切变线'],
  },
  {
    id: 'heavy-rain-score',
    name: '强降水风险评分',
    category: '灾害天气',
    icon: '雨',
    description: '从水汽、动力、热力、持续性和模式一致性生成风险证据链。',
    status: 'built-in',
    tags: ['评分', '强降水', '风险'],
  },
  {
    id: 'forecast-writing',
    name: '预报稿件生成',
    category: '内容创作',
    icon: '稿',
    description: '根据结构化气象结论和业务模板生成预报、专题与决策服务稿。',
    status: 'built-in',
    tags: ['写稿', '模板', '审核'],
  },
  {
    id: 'docx-template',
    name: 'Word 模板填充',
    category: '办公成果物',
    icon: 'W',
    description: '将结构化内容、图表与图片写入 Word 模板并导出 PDF。',
    status: 'planned',
    tags: ['DOCX', '模板', 'PDF'],
  },
  {
    id: 'spreadsheet-analysis',
    name: 'Excel 统计与制图',
    category: '办公成果物',
    icon: 'X',
    description: '读取表格、生成统计、公式、图表和降水数据汇总。',
    status: 'planned',
    tags: ['XLSX', '统计', '图表'],
  },
  {
    id: 'presentation-generation',
    name: 'PPT 汇报生成',
    category: '办公成果物',
    icon: 'P',
    description: '根据报告大纲、模板和气象图件生成汇报材料。',
    status: 'planned',
    tags: ['PPTX', '汇报', '图件'],
  },
  {
    id: 'pdf-research',
    name: 'PDF 资料摘要',
    category: '知识处理',
    icon: 'PDF',
    description: '提取 PDF 资料中的结论、表格、引用和业务规则。',
    status: 'planned',
    tags: ['PDF', '知识库', '引用'],
  },
  {
    id: 'nc-grib-inspection',
    name: 'NC / GRIB 数据检查',
    category: '数据智能',
    icon: 'NC',
    description: '检查变量、维度、单位、坐标、缺测值和时空范围。',
    status: 'planned',
    tags: ['NetCDF', 'GRIB', '元数据'],
  },
]);

window.METEOMATE_CONNECTORS = Object.freeze([
  {
    id: 'playwright-browser',
    name: '浏览器操作',
    category: '网页与自动化',
    icon: '览',
    description: '打开网页、读取内容、截图，并完成点击、输入和表单操作。',
    status: 'available',
    tags: ['Playwright', '网页', '自动化'],
    preset: window.MeteoMateBrowserConnector.PRESET,
  },
  {
    id: 'local-workspace',
    name: '本地项目工作区',
    category: '文件与项目',
    icon: '夹',
    description: '授权本地项目目录，后续接入 Safe Workspace MCP、Diff、快照与回滚。',
    status: 'beta',
    tags: ['文件', '项目', '审批'],
  },
  {
    id: 'weather-data',
    name: '气象数据中心',
    category: '气象数据',
    icon: '数',
    description: '接入实况、EC 模式、雷达、卫星、探空、站点和格点数据。',
    status: 'planned',
    tags: ['实况', '模式', '雷达'],
  },
  {
    id: 'weather-diagnosis',
    name: '天气诊断算法服务',
    category: '气象算法',
    icon: '诊',
    description: '提供高低压、槽线、切变线、锋面、急流与灾害天气评分。',
    status: 'planned',
    tags: ['诊断', '天气系统', '评分'],
  },
  {
    id: 'gis-map',
    name: 'GIS 制图服务',
    category: '气象可视化',
    icon: '图',
    description: '生成等值线、色斑图、天气系统、站点标注和业务地图。',
    status: 'planned',
    tags: ['GIS', '地图', '图层'],
  },
  {
    id: 'artifact-docx',
    name: 'Office Artifact Service',
    category: '办公',
    icon: '文',
    description: '统一生成 DOCX、XLSX、PPTX、PDF、HTML 和图片成果物。',
    status: 'planned',
    tags: ['Word', 'Excel', 'PPT'],
  },
  {
    id: 'knowledge-base',
    name: '气象知识库',
    category: '知识服务',
    icon: '知',
    description: '检索业务规范、历史过程、技术手册、论文和内部资料。',
    status: 'planned',
    tags: ['知识库', 'RAG', '引用'],
  },
]);
