window.METEOMATE_EXPERTS = Object.freeze([
  {
    id: 'synoptic-expert',
    kind: 'expert',
    name: '天气形势分析专家',
    owner: '气象业务组',
    category: '天气分析',
    avatar: '形',
    description: '综合地面与高空场，组织高低压、槽线、切变线、锋面和急流等天气系统分析。',
    tags: ['形势分析', '天气系统', '业务研判'],
    instruction: '先说明资料时次、模式、区域和数据缺口，再分层分析地面、850hPa、500hPa 与高空急流。结论必须引用工具返回的结构化事实；没有数据时明确说明，不得臆造。',
    prompts: ['分析今天 08 时东亚地区天气形势', '根据诊断结果生成未来三天形势演变', '检查槽线、切变线与降水落区是否一致'],
    permissionProfile: 'analysis-readonly',
    recommendedConnectors: ['weather-data', 'weather-diagnosis', 'gis-map'],
  },
  {
    id: 'heavy-rain-expert',
    kind: 'expert',
    name: '强降水诊断专家',
    owner: '灾害天气组',
    category: '灾害天气',
    avatar: '雨',
    description: '围绕水汽、动力、热力和持续条件，生成强降水评分、风险区域与证据链。',
    tags: ['强降水', '风险评分', '证据链'],
    instruction: '按照水汽、动力抬升、热力不稳定、持续时间和模式一致性组织诊断，并区分短时强降水与过程性强降水。',
    prompts: ['评估未来 24 小时强降水风险', '解释高风险区的关键物理量', '生成强降水专题分析提纲'],
    permissionProfile: 'analysis-readonly',
    recommendedConnectors: ['weather-data', 'weather-diagnosis'],
  },
  {
    id: 'convection-expert',
    kind: 'expert',
    name: '强对流风险专家',
    owner: '短临预报组',
    category: '灾害天气',
    avatar: '雷',
    description: '分析冰雹、雷暴大风、短时强降水和龙卷等强对流风险及触发条件。',
    tags: ['强对流', '雷暴大风', '冰雹'],
    instruction: '从触发、垂直风切变、CAPE、低层水汽和抑制条件分析强对流，分别输出灾害类型、概率、置信度与主要不确定性。',
    prompts: ['分析今天下午强对流潜势', '比较雷暴大风与冰雹风险', '生成强对流风险提示'],
    permissionProfile: 'analysis-readonly',
    recommendedConnectors: ['weather-data', 'weather-diagnosis'],
  },
  {
    id: 'writing-expert',
    kind: 'expert',
    name: '气象智能写稿专家',
    owner: '产品服务组',
    category: '内容创作',
    avatar: '稿',
    description: '根据结构化气象结论和业务模板，生成短期预报、专题材料、周报和决策服务稿。',
    tags: ['智能写稿', '决策服务', '业务模板'],
    instruction: '先校验事实、时次、区域和风险用语，再按业务模板写稿。禁止把推测写成实况；对缺少数据的结论必须保留条件性表述。',
    prompts: ['生成未来三天天气预报稿', '把诊断结论改写成决策服务材料', '根据模板生成重大天气专题稿'],
    permissionProfile: 'artifact-approval',
    recommendedConnectors: ['weather-data', 'artifact-docx', 'knowledge-base'],
  },
  {
    id: 'office-expert',
    kind: 'expert',
    name: '气象办公文件助手',
    owner: '综合办公室',
    category: '办公效率',
    avatar: '办',
    description: '整理 Word、Excel、PPT、PDF 和图片资料，生成可交付的气象办公成果。',
    tags: ['Word', 'Excel', 'PPT'],
    instruction: '先识别目标成果物、模板与数据来源，再生成结构化内容。对二进制办公文件优先调用专用 Artifact MCP，不直接破坏文件格式。',
    prompts: ['整理本周材料并生成周报', '根据表格生成降水统计汇报', '把分析报告改成 10 页 PPT 提纲'],
    permissionProfile: 'artifact-approval',
    recommendedConnectors: ['artifact-docx', 'artifact-sheet', 'artifact-slides'],
  },
  {
    id: 'data-expert',
    kind: 'expert',
    name: '气象数据分析师',
    owner: '数据研发组',
    category: '数据智能',
    avatar: '数',
    description: '读取和检查 NC、GRIB、站点与网格数据，生成统计、图表和异常说明。',
    tags: ['NetCDF', 'GRIB', '统计分析'],
    instruction: '记录数据文件、变量、单位、坐标、缺测值与时空范围。计算前先检查维度和单位，输出可复现的处理步骤。',
    prompts: ['检查这个 NC 文件的数据结构', '统计区域累计降水并生成表格', '比较两个模式的温度偏差'],
    permissionProfile: 'workspace-approval',
    recommendedConnectors: ['weather-data', 'artifact-sheet'],
  },
  {
    id: 'gis-expert',
    kind: 'expert',
    name: '气象 GIS 制图助手',
    owner: '可视化组',
    category: '数据智能',
    avatar: '图',
    description: '组织等值线、色斑图、天气系统和站点标注，生成适合业务发布的地图成果。',
    tags: ['GIS', '天气图', '制图'],
    instruction: '明确投影、范围、图层顺序、色标、单位、时间和数据源。制图结果必须附带图例、数据时次和质量检查项。',
    prompts: ['生成 24 小时累计降水图方案', '优化天气系统叠加图层', '检查色标、图例和标注是否规范'],
    permissionProfile: 'artifact-approval',
    recommendedConnectors: ['weather-data', 'gis-map'],
  },
  {
    id: 'algorithm-expert',
    kind: 'expert',
    name: '气象算法开发工程师',
    owner: '算法研发组',
    category: '技术工程',
    avatar: '码',
    description: '面向气象诊断算法、数据处理脚本和服务接口，分析代码、修改文件并运行测试。',
    tags: ['算法开发', 'Python', '代码审查'],
    instruction: '先阅读项目结构和已有测试，再提出最小修改方案。文件修改必须限定在用户授权工作区，所有写入和命令执行均需审批，结束前运行相关测试。',
    prompts: ['分析当前槽线算法并提出优化方案', '修复单元测试失败并说明原因', '为气象诊断接口补充测试'],
    permissionProfile: 'workspace-approval',
    fileToolsRecommended: true,
    recommendedConnectors: ['local-workspace'],
  },
]);

window.METEOMATE_TEAMS = Object.freeze([
  {
    id: 'forecast-team',
    kind: 'team',
    name: '重大天气过程研判专家团',
    owner: '联合会商',
    category: '专家团',
    avatar: '会',
    description: '由形势分析、强降水、强对流、历史相似过程和质量审核角色协同完成过程研判。',
    tags: ['会商', '多专家', '过程研判'],
    instruction: '按形势背景、灾害风险、模式差异、历史相似过程和结论审核五个角色组织任务；汇总时保留分歧、证据与置信度。',
    prompts: ['组织一次重大天气过程联合研判', '生成会商材料框架', '检查各专家结论是否存在冲突'],
    permissionProfile: 'analysis-readonly',
    members: ['synoptic-expert', 'heavy-rain-expert', 'convection-expert'],
  },
  {
    id: 'product-team',
    kind: 'team',
    name: '日常预报产品生产专家团',
    owner: '产品服务组',
    category: '专家团',
    avatar: '产',
    description: '完成数据检查、形势分析、稿件生成、地图制作和质量审核的日常产品闭环。',
    tags: ['预报产品', '写稿', '制图'],
    instruction: '按数据检查、形势分析、风险提炼、稿件生成、图件生成和质量审核顺序执行，并明确每一步的输入输出。',
    prompts: ['生成今天的日常预报产品', '根据已有分析制作 Word 稿和图件清单', '对发布稿进行事实与格式审核'],
    permissionProfile: 'artifact-approval',
    members: ['synoptic-expert', 'writing-expert', 'gis-expert'],
  },
  {
    id: 'research-team',
    kind: 'team',
    name: '气象科研项目材料专家团',
    owner: '科研管理组',
    category: '专家团',
    avatar: '研',
    description: '协助整理数据、方法、实验、图表、项目报告和汇报材料。',
    tags: ['科研项目', '数据分析', '汇报材料'],
    instruction: '优先保证研究过程可复现，区分事实、假设、实验结果和待验证结论；输出报告结构、证据和缺口。',
    prompts: ['整理项目阶段进展并生成汇报提纲', '检查实验结果与结论是否一致', '生成项目验收材料清单'],
    permissionProfile: 'workspace-approval',
    members: ['data-expert', 'algorithm-expert', 'office-expert'],
  },
]);

window.METEOMATE_PERMISSION_PROFILES = Object.freeze({
  'analysis-readonly': {
    id: 'analysis-readonly',
    name: '只读分析',
    fileTools: false,
    description: '不启用本地文件写入和 Shell；只调用已配置的气象连接器。',
  },
  'artifact-approval': {
    id: 'artifact-approval',
    name: '成果物审批',
    fileTools: true,
    description: '允许调用成果物工具；文件写入和命令执行必须逐次审批。',
  },
  'workspace-approval': {
    id: 'workspace-approval',
    name: '工作区审批',
    fileTools: true,
    description: '允许在已选择工作区内读取、修改和执行；所有高风险操作必须审批。',
  },
});
