window.METEOMATE_SCENES = Object.freeze([
  {
    id: 'synoptic',
    title: '天气形势分析',
    subtitle: '中央台实况图、高低压、槽线与切变线综合研判',
    group: 'forecast',
    icon: 'synoptic',
    gradient: 'scene-blue',
    expertId: 'synoptic-expert',
  },
  {
    id: 'severe-weather',
    title: '灾害天气',
    subtitle: '强降水、强对流与风险区域分析',
    group: 'forecast',
    icon: 'severe',
    gradient: 'scene-purple',
    expertId: 'heavy-rain-expert',
  },
  {
    id: 'content',
    title: '产品制作',
    subtitle: '预报稿、专题材料、Word 与 PPT 成果物',
    group: 'products',
    icon: 'content',
    gradient: 'scene-amber',
    expertId: 'writing-expert',
  },
  {
    id: 'data',
    title: '数据与科研',
    subtitle: 'NC/GRIB 分析、算法调试与项目材料',
    group: 'data',
    icon: 'data',
    gradient: 'scene-cyan',
    expertId: 'data-expert',
  },
  {
    id: 'operations',
    title: '运维保障',
    subtitle: '系统巡检、告警研判、故障定位与恢复验证',
    group: 'operations',
    icon: 'operations',
    gradient: 'scene-purple',
    expertId: 'operations-expert',
  },
]);
